<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="MAIN" Id="{c97cf794-3590-4837-b147-9c26d66ccec6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	PLCVar:PLCStruct;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>